services:
  geo-service:
    build: ./geo_service
    image: geo_service:latest
    deploy:
      replicas: 1

  formatter-service:
    build: ./formatter_service
    image: formatter_service:latest
    deploy:
      replicas: 1
  
  nginx:
    build: ./nginx
    image: nginx_proxy:latest
    ports:
      - "8080:80"
    deploy:
      replicas: 1