events {
    worker_connections 1024;
}
http {
    upstream geo_backend {
        server weather_service_geo-service:8001;
    }
    upstream formatter_backend {
        server weather_service_formatter-service:8002;
    }
    server {
        listen 80;

        location /geo/ {
            proxy_pass http://geo_backend/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }
        location /formatter/ {
            proxy_pass http://formatter_backend/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        } 
    }
}